apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gitlab.fullname" . }}
  namespace: {{ .Values.gitlab.namespace }}
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ template "gitlab.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "gitlab.fullname" . }}
    spec:
      containers:
      - args:
        - run
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ template "gitlab.fullname" . }}
        volumeMounts:
        - mountPath: /etc/gitlab-runner
          name: config
        - mountPath: /etc/ssl/certs
          name: cacerts
          readOnly: true
      restartPolicy: Always
      volumes:
      - configMap:
          name: gitlab-runner
        name: config
      - hostPath:
          path: /usr/share/ca-certificates/mozilla
        name: cacerts
