apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "geth.fullname" . }}
  labels:
    app: {{ template "geth.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "geth.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: {{ template "geth.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["/geth", "--networkid", "{{ .Values.networkId }}", "--syncmode", "{{ .Values.syncMode }}", "--rpc", "--rpcapi", "{{ .Values.rpcApi }}", "--rpcaddr", "0.0.0.0", "--rpcport", "{{ .Values.rpcPort }}", "--ws", "--wsaddr", "0.0.0.0", "--wsport", "{{ .Values.wsPort }}", "--wsapi", "{{ .Values.wsApi }}", "--wsorigins", "{{ .Values.wsOrigins }}"]
          resources:
  {{ toYaml .Values.resources | indent 10 }}
          ports:
            - name: rpc
              containerPort: {{ .Values.rpcPort }}
            - name: ws
              containerPort: {{ .Values.wsPort }}
          volumeMounts:
            - name: data
              mountPath: /root
      initContainers:
        - name: mkdir-{{ template "geth.fullname" . }}
          image: busybox
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: [ "sh", "-c", "mkdir -p /root/node"]
          resources:
  {{ toYaml .Values.resources | indent 10 }}
          volumeMounts:
            - name: data
              mountPath: /root
        - name: setpw-{{ template "geth.fullname" . }}
          image: busybox
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["echo", "{{ .Values.walletpassword }}", ">/root/node/password.txt"]
          resources:
  {{ toYaml .Values.resources | indent 10 }}
          volumeMounts:
            - name: data
              mountPath: /root
        - name: getgenesis-{{ template "geth.fullname" . }}
          image: busybox
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["echo", "{{ .Values.genesisjson }}", ">/root/node/genesis.json"]
          resources:
  {{ toYaml .Values.resources | indent 10 }}
          volumeMounts:
            - name: data
              mountPath: /root
        - name: walletinit-{{ template "geth.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["/geth", "--datadir", "/root/node/", "--password", "/root/node/password.txt", "account", "new"]
          resources:
  {{ toYaml .Values.resources | indent 10 }}
          volumeMounts:
            - name: data
              mountPath: /root
        - name: blockchainit-{{ template "geth.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["/geth", "--datadir", "/root/node/", "init", "/root/node/genesis.json"]
          resources:
  {{ toYaml .Values.resources | indent 10 }}
          volumeMounts:
            - name: data
              mountPath: /root
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "geth.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
